services:
  traefik:
    image: docker.io/traefik:${TRAEFIK_VERSION:-v3.1}
    container_name: traefik-dev
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:ro
      - ./traefik-dev.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic/dev:/etc/traefik/sites/config:ro
      - ./dynamic/shared:/etc/traefik/sites/shared:ro
      - ./data:/data
      - ./logs:/var/log/traefik
      - ".:/plugins-local/src/github.com/acouvreur/traefik-modsecurity-plugin"
    networks:
      - traefik
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # waf:
  #   image: docker.io/owasp/modsecurity-crs:4.2.0-apache-202405220605
  #   container_name: waf-dev
  #   restart: unless-stopped
  #   environment:
  #     - PARANOIA=1
  #     - ANOMALY_INBOUND=10
  #     - ANOMALY_OUTBOUND=5
  #     - BACKEND=http://dummy-dev
  #   networks:
  #     - traefik

  # dummy:
  #   image: docker.io/traefik/whoami:${WHOAMI_VERSION:-latest}
  #   container_name: dummy-dev
  #   restart: unless-stopped
  #   networks:
  #     - traefik

  whoami:
    image: docker.io/traefik/whoami:${WHOAMI_VERSION:-latest}
    container_name: whoami-dev
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    driver: bridge
    external: true
